### ISSUE TITLE
Navigation to file manager after video playback 

### ISSUE THREAD

**Issue by yohanilluminated** [mpv-android/mpv-android#730] opened 2023-06-10 10:03 UTC
I have observed that when I play a video from the file manager with mpv, if I press back or the video ends  it returns to mpv home screen instead of going back to the file manager where the video was selected.

### Additional information
Also a button to select the screen orientation in player interface will be also great.

**Comment by sfan5** [comment] 2023-06-10 10:37
duplicate of #647

> Also a button to select the screen orientation in player interface will be also great.

This button will appear if you set the orientation in settings to anything except "Auto".

**Closed by sfan5** 2023-06-10 10:37 UTC
Labels: feature request

**Comment by yohanilluminated** [comment] 2023-06-10 12:23
What about the first request?

**Comment by sfan5** [comment] 2023-06-10 13:10
It's a duplicate of the other issue I linked, there is no known solution.
