### ISSUE TITLE
MPV crashes with vo=gpu-next + profile=high-quality on pixel 8 pro

### ISSUE THREAD

**Issue by rshxyz** [mpv-android/mpv-android#955] opened 2024-07-08 20:52 UTC
### Important information

Android version:
14

mpv-android version:
```
mpv-android 2024-06-05-release / 8037 (release)
mpv v0.38.0-432-g112fa549be Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Jun  5 2024 23:47:01
libplacebo version: v7.349.0 (v7.349.0-rc1-1-g79a2efcb)
FFmpeg version: n7.0.1-6-gf0b747ef1a
FFmpeg library versions:
   libavutil       59.8.100
   libavcodec      61.3.100
   libavformat     61.1.100
   libswscale      8.1.100
   libavfilter     10.1.100
   libswresample   5.1.100

Configuration: -Diconv=disabled -Dlua=enabled -Dlibmpv=true -Dcplayer=false -Dmanpage-build=disabled -Ddefault_library=shared --cross-file=/var/tmp/mpv-android/buildscripts/prefix/arm64/crossfile.txt
List of enabled features: android android-media-ndk av-channel-layout avif-muxer build-date cplugins dvbin egl-android ffmpeg gl glibc-thread-name gpl jpegxl lavu-uuid libass libavdevice libdl libplacebo linux-fstatfs lua opensles posix ppoll pthread-condattr-setclock vector vt.h zlib
```

Which version of mpv-android introduced the problem (if known):
IDK
### Description

Describe your issue in detail here.
MPV crashes when watching video files

Use the following mpv.config
vo=gpu-next
profile=high-quality

### Log output

```
type: crash
osVersion: google/husky/husky:14/AP2A.240705.005/2024070201:user/release-keys
package: is.xyz.mpv:8037
process: is.xyz.mpv
processUptime: 0 + 0 ms
installer: com.android.vending

signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000370

backtrace:
      #00 pc 00000000009d0b00  /vendor/lib64/egl/libGLES_mali.so (glescore_submission::deref_on_reset(gfx::util::dynamic_array<cutils_refcount*> const&)+16) (BuildId: c3a26ffd1f79978c)
      #01 pc 00000000009c3164  /vendor/lib64/egl/libGLES_mali.so (gles_fb_object_flush_graphics_nx+244) (BuildId: c3a26ffd1f79978c)
      #02 pc 000000000098392c  /vendor/lib64/egl/libGLES_mali.so (gles2_queryp_flush+108) (BuildId: c3a26ffd1f79978c)
      #03 pc 000000000098449c  /vendor/lib64/egl/libGLES_mali.so (gles_queryp_object_flush_for_result+44) (BuildId: c3a26ffd1f79978c)
      #04 pc 0000000000983080  /vendor/lib64/egl/libGLES_mali.so (gles2_queryp_get_query_object_getv+400) (BuildId: c3a26ffd1f79978c)
      #05 pc 00000000004f9104  /data/app/~~jZP-O301uyKLN7oEeHQkHw==/is.xyz.mpv-uPnodKNwrlxyQ30eY_W6tQ==/split_config.arm64_v8a.apk!libmpv.so (offset 0x1492000)
      #06 pc 00000000004b33f4  /data/app/~~jZP-O301uyKLN7oEeHQkHw==/is.xyz.mpv-uPnodKNwrlxyQ30eY_W6tQ==/split_config.arm64_v8a.apk!libmpv.so (offset 0x1492000)
      #07 pc 00000000004b0db8  /data/app/~~jZP-O301uyKLN7oEeHQkHw==/is.xyz.mpv-uPnodKNwrlxyQ30eY_W6tQ==/split_config.arm64_v8a.apk!libmpv.so (offset 0x1492000) (pl_dispatch_finish+1456)
      #08 pc 0000000000486414  /data/app/~~jZP-O301uyKLN7oEeHQkHw==/is.xyz.mpv-uPnodKNwrlxyQ30eY_W6tQ==/split_config.arm64_v8a.apk!libmpv.so (offset 0x1492000) (pl_render_image_mix+3928)
      #09 pc 0000000000306038  /data/app/~~jZP-O301uyKLN7oEeHQkHw==/is.xyz.mpv-uPnodKNwrlxyQ30eY_W6tQ==/split_config.arm64_v8a.apk!libmpv.so (offset 0x1492000)
      #10 pc 00000000002f910c  /data/app/~~jZP-O301uyKLN7oEeHQkHw==/is.xyz.mpv-uPnodKNwrlxyQ30eY_W6tQ==/split_config.arm64_v8a.apk!libmpv.so (offset 0x1492000)
      #11 pc 00000000000795dc  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204) (BuildId: 5dc060303292ee294ec0e176f3fed4b3)
      #12 pc 0000000000069fa4  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: 5dc060303292ee294ec0e176f3fed4b3)
```

**Comment by sfan5** [comment] 2024-07-10 09:56
duplicate of #947

**Closed by sfan5** 2024-07-10 09:56 UTC
