### ISSUE TITLE
Save position on quit not working properly 

### ISSUE THREAD

**Issue by Srijan-07** [mpv-android/mpv-android#932] opened 2024-06-02 11:55 UTC
Android version:14

mpv-android version:2024-04-09-release

Whenever I open the video that I left watching somewhere it doesn't resume and start from the beginning despite enabling save position on quit.

**Comment by sfan5** [comment] 2024-06-02 14:28
Log file?

**Comment by NBruderman** [comment] 2024-06-05 21:55
I must say I experience the same issues... I'll try to get a log file later, but I can confirm 2 things:
1. The issue is inconsistent, sometimes it works fine, and sometimes not
2. It happens when I open a file from an external file manager (MiX in my case)

**Comment by sfan5** [comment] 2024-06-05 22:15
that would be a duplicate of #542

**Comment by Srijan-07** [comment] 2024-06-06 01:21
> I must say I experience the same issues... I'll try to get a log file later, but I can confirm 2 things:
> 
> 1. The issue is inconsistent, sometimes it works fine, and sometimes not
> 2. It happens when I open a file from an external file manager (MiX in my case)

Yeah the issue is inconsistent, in my case the feature only worked 1 or 2 time of the many times I tried to do it

**Comment by Srijan-07** [comment] 2024-06-06 01:22
> Log file?

I don't know how to do that sorry :)

**Comment by Srijan-07** [comment] 2024-06-06 01:25
> Log file?

I don't know how to do that sorry :)

**Comment by sfan5** [comment] 2024-06-07 11:24
The issue template tells you how to produce a log file.

**Closed** 2024-06-09 16:42 UTC
