### ISSUE TITLE
Volume boost above 100%

### ISSUE THREAD

**Issue by MyNameIsAnujRanjan** [mpv-android/mpv-android#893] opened 2024-04-11 08:11 UTC
Add volume boost up to 200% in MPV just like in VLC or MX Player upon enabling SW decoder

**Comment by sfan5** [comment] 2024-04-13 12:23
duplicate of #320

**Closed by sfan5** 2024-04-13 12:23 UTC
Labels: feature request

**Comment by MyNameIsAnujRanjan** [comment] 2024-04-15 07:36
This is already has been reported but it not solved please mark one of them open

**Comment by sfan5** [comment] 2024-04-15 09:31
The issue I linked is open.
