### ISSUE TITLE
When open second video file. Will not play.

### ISSUE THREAD

**Issue by JoinnA** [mpv-android/mpv-android#230] opened 2020-01-17 23:08 UTC
Hello,

I use the current mpv Android version: 2019-11-03-alpha on my Android 9 Samsung Galaxy S9+ device (no root).

I only use the standard File Manager app from the Android device to open videos (recorded videos from the camera).

When I open the first video file, exactly this video file is played in mpv. Background playback function is on.

I quickly go back to standard File Manager app and tap a second video file. But when I do that in mpv not the second video file is played, but only the first one 😥

What now?

**Comment by sfan5** [comment] 2020-01-19 14:16
duplicate of #162

**Closed by sfan5** 2020-01-19 14:16 UTC
Labels: bug
