### ISSUE TITLE
Video playing is flickering on android 9-10

### ISSUE THREAD

**Issue by fifa87** [mpv-android/mpv-android#284] opened 2020-06-23 15:19 UTC
I knew mpv was most open-source cross-platform player engine.
But I didn't know it has critical error. I can't understand other developer couldn't found this.
I have built android project by using https://github.com/mpv-player/mpv-examples/tree/master/libmpv/qml.(last committed)
I have used libmpv and other libraries of https://github.com/mpv-android/mpv-android.(last committed)
On Windows and most phones, it was ok.(android 8 lower)
But on some phones(i.e. Samsung Galaxy A30, Honor 9 Lite, vivo s1, Realme 3 rmx 1825, ... . android 9 higher), videos are flickering.
Please look at this link video.
I have uploaded captured videos.
https://drive.google.com/file/d/1EaVYDEt1_nzC-UjzG1NxWeZPC7CMypzi/view?usp=sharing
https://drive.google.com/file/d/1R5OYsI3rvXPhp0Ppj32Y2K16VCvbe0Ht/view?usp=sharing
I was humiliated from my clients.

**Comment by fifa87** [comment] 2020-06-23 15:35
It is very critical problem. many hundreds phones are reported.

**Comment by sfan5** [comment] 2020-06-23 15:49
Google Play user reviews do not indicate any problems with flickering (or similar) in mpv-android.
Since you are using the Qt binding for your app, the problem may be with that specific code and not mpv.

This is also a duplicate of #280.

**Closed by sfan5** 2020-06-23 15:49 UTC
