### ISSUE TITLE
hwdec: mediacodec fails when transitioning to the next item in a playlist

### ISSUE THREAD

**Issue by jarnedemeulemeester** [mpv-android/mpv-android#966] opened 2024-08-03 21:16 UTC
### Important information

Android version: 15 beta 4.1

mpv-android version: 2024-06-05

### Description

When playing multiple items (holding down on a folder to play all items in it) hardware decoding using `mediacodec` initially works fine. But when transitioning to the next item the hardware decoder fails and falls back to `mediacodec-copy` (or software decoding when `mediacodec` is forced via `--hwdec=mediacodec`).

### Log output

Log output of transition to next item:
```
08-03 22:45:34.736 25131 25695 V mpv     : [ffmpeg/video:v] h264_mediacodec: Using surface 0xb400006ed8278f50
08-03 22:45:34.750 25131 25724 D SurfaceUtils: connecting to surface 0xb400006f4843cf20, reason connectToSurface
08-03 22:45:34.750 25131 25724 E BufferQueueProducer: [ImageReader-16x16f22u256m5-25131-3](id:622b0000001c,api:3,p:25131,c:25131) connect: already connected (cur=3 req=3)
08-03 22:45:34.750 25131 25724 E SurfaceUtils: Failed to connect to surface 0xb400006f4843cf20, err -22
08-03 22:45:34.750 25131 25724 E MediaCodec: nativeWindowConnect/surfaceConnectWithListener returned an error: Invalid argument (-22)
08-03 22:45:34.750 25131 25689 E MediaCodec: configure failed with err 0xffffffea, resetting...
08-03 22:45:34.768 25131 25695 V mpv     : [ffmpeg:error] amediacodec: java.lang.IllegalArgumentException: 
08-03 22:45:34.768 25131 25695 V mpv     : [ffmpeg/video:error] h264_mediacodec: Failed to configure codec c2.exynos.h264.decoder (status = -542398533) with format {csd-1=java.nio.DirectByteBuffer[pos=0 lim=8 cap=8], mime=video/avc, width=320, csd-0=java.nio.DirectByteBuffer[pos=0 lim=26 cap=26], height=240}
08-03 22:45:34.768 25131 25695 V mpv     : [ffmpeg/video:error] h264_mediacodec: MediaCodec 0xb400006eb82b1520 failed to start
08-03 22:45:34.769 25131 25695 V mpv     : [vd:error] Could not open codec.
08-03 22:45:34.769 25131 25695 V mpv     : [vd:v] Attempting next decoding method after failure of h264_mediacodec-mediacodec.
```
Full log: [mpv-mediacodec-transition.log](https://github.com/user-attachments/files/16482917/mpv-mediacodec-transition.log)

### Additional information

This issue can be reproduced on all of my devices. It does not seem to be specific to a particular device or Android version.
Tested on my Pixel 8 running Android 15 and Sony A95K running Android 10.

All files tested played fine individually using `mediacodec`.

Using only `mediacodec-copy` does work fine. Transitioning to the next item stays on `mediacodec-copy`.

I have been looking at the source code of both mpv and ffmpeg for hours but I'm unable to figure where it's going wrong. :sweat_smile: 
It seems like the surface is never released and that's why the next MediaCodec instance fails to connect to it. However I'm not sure of this.

**Comment by sfan5** [comment] 2024-08-03 21:38
for further investigation enabling debug logging for ffmpeg might be helpful (there's some e.g. [here](https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/mediacodecdec_common.c))

The `AImageReader` is created once when the hwdec driver is initialized and reused from then on:
https://github.com/mpv-player/mpv/blob/5f768a688b706cf94041adf5bed7c7004af2ec5a/video/out/hwdec/hwdec_aimagereader.c#L128
what's a bit weird is that the "[ffmpeg/video:v] h264_mediacodec: Using surface" log line shows two different pointers in those cases

results of further testing: I can reproduce this on my Galaxy A25 (Android 14), it's just that I've never noticed it.
Having a file that doesn't use hwdec inbetween will cause HW+ to work again just one time.

**Comment by sfan5** [comment] 2024-08-03 22:09
testing reveals that ffmpeg apparently holds onto the surface far too long
this isn't necessarily ffmpeg's fault however

```
attempt 1:
08-04 00:03:29.245 11578 11650 V mpv     : [ffmpeg/video:v] h264_mediacodec: Using surface 0x71294189d0
08-04 00:03:29.371 11578 11650 V mpv     : [ffmpeg/video:warn] h264_mediacodec: MediaCodec 0x70d949b390 started successfully

attempt 2:
08-04 00:03:35.388 11578 11650 V mpv     : [ffmpeg/video:v] h264_mediacodec: Using surface 0x7129433d90
08-04 00:03:35.388 11578 11650 V mpv     : [ffmpeg:error] amediacodec: java.lang.IllegalArgumentException: 
08-04 00:03:35.388 11578 11650 V mpv     : [ffmpeg/video:error] h264_mediacodec: MediaCodec 0x70d95026b0 failed to start
08-04 00:03:35.388 11578 11650 V mpv     : [ffmpeg:error] Unref surface 0x7129433d90

later:
08-04 00:03:35.389 11578 11650 V mpv     : [ffmpeg:error] Unref surface 0x71294189d0

**Comment by sfan5** [comment] 2024-08-03 22:41
turns out the relevant part is the MediaCodec instance itself and not some ref on the surface (which would be weird anyway).
If we expedite the deletion of the codec on close the problem goes away:
```diff
diff --git a/libavcodec/mediacodecdec_common.c b/libavcodec/mediacodecdec_common.c
--- a/libavcodec/mediacodecdec_common.c
+++ b/libavcodec/mediacodecdec_common.c
@@ -841,6 +852,12 @@ int ff_mediacodec_dec_flush(AVCodecContext *avctx, MediaCodecDecContext *s)
 
 int ff_mediacodec_dec_close(AVCodecContext *avctx, MediaCodecDecContext *s)
 {
+    atomic_fetch_add(&s->serial, 1);
+    if (s->codec) {
+        ff_AMediaCodec_delete(s->codec);
+        s->codec = NULL;
+    }
+
     ff_mediacodec_dec_unref(s);
 
     return 0;
```
this is logical because buffers should not outlive the codec itself

maybe better fixed in mpv tho

**Comment by sfan5** [comment] 2024-08-03 23:33
culprit inside mpv:
<pre>
mp_image_destructor at mp_image.c:?
ta_free at ta.c:?
mp_image_unrefp at mp_image.c:?
unref_current_image at video.c:?
gl_video_config at video.c:?
reconfig at vo_gpu.c:?
run_reconfig at vo.c:?
mp_dispatch_queue_process at dispatch.c:?
vo_thread at vo.c:?
</pre>
this is `p->image` in vo_gpu's gl struct
though vo.c is probably also keeping it alive via `in->current_frame`

unfortunately it's intentional that mpv is doing this. so not a trivial fix.

**Comment by jarnedemeulemeester** [comment] 2024-08-04 09:32
> turns out the relevant part is the MediaCodec instance itself and not some ref on the surface (which would be weird anyway). If we expedite the deletion of the codec on close the problem goes away:
> 
> ```diff
> diff --git a/libavcodec/mediacodecdec_common.c b/libavcodec/mediacodecdec_common.c
> --- a/libavcodec/mediacodecdec_common.c
> +++ b/libavcodec/mediacodecdec_common.c
> @@ -841,6 +852,12 @@ int ff_mediacodec_dec_flush(AVCodecContext *avctx, MediaCodecDecContext *s)
>  
>  int ff_mediacodec_dec_close(AVCodecContext *avctx, MediaCodecDecContext *s)
>  {
> +    atomic_fetch_add(&s->serial, 1);
> +    if (s->codec) {
> +        ff_AMediaCodec_delete(s->codec);
> +        s->codec = NULL;
> +    }
> +
>      ff_mediacodec_dec_unref(s);
>  
>      return 0;
> ```


Testing this indeed seems to solve the problem, thanks! 
I will be using this patch in my build of libmpv.

I wish I could help develop a better solution in mpv itself but I'm afraid I'm not not skilled enough for that. :sweat_smile:

**Comment by sfan5** [comment] 2024-08-04 10:09
> I will be using this patch in my build of libmpv.

Don't. It's literally just a quick hacky patch and *will* cause crashes.

**Comment by jarnedemeulemeester** [comment] 2024-08-04 10:44
> Don't. It's literally just a quick hacky patch and *will* cause crashes.

Oh okay, I will wait for a proper fix then

**Comment by sfan5** [comment] 2024-08-07 16:31
possible fix in ffmpeg: https://patchwork.ffmpeg.org/project/ffmpeg/list/?series=12615
possible fix in mpv: https://github.com/mpv-player/mpv/pull/14631

either suffices

**Comment by jarnedemeulemeester** [comment] 2024-08-10 20:49
Fix in ffmpeg seems to work fine.
The fix in mpv however still gives me the same original error.

**Comment by sfan5** [comment] 2024-08-17 18:09
Fix upstreamed.

**Closed by sfan5** 2024-08-17 18:09 UTC
Labels: bug, hwdec
