### ISSUE TITLE
Pause with Single tap

### ISSUE THREAD

**Issue by lodgerz** [mpv-android/mpv-android#881] opened 2024-03-08 21:42 UTC
Hi, is it possible to pause the video with 1 single tap? in the options there is only the option for Double tap.
Then is it possible to make it so that when you pause the OSD panel disappears?
Thanks.

**Comment by da3dsoul1** [comment] 2024-03-09 10:56
Only double tap is supported

**Comment by sfan5** [comment] 2024-07-27 10:11
logical duplicate of #520

**Closed by sfan5** 2024-07-27 10:11 UTC
Labels: feature request, user interface
