### ISSUE TITLE
Add feature to supply custom mpv.conf via adb intent extras

### ISSUE THREAD

**Issue by tathastu871** [mpv-android/mpv-android#664] opened 2023-02-12 18:12 UTC
Describe the wanted behaviour of the new feature and potential usecases for it here.

Add a functionality to supply custom mpv.conf to adb intent
it will help set custom options and title per file basis

**Comment by sfan5** [comment] 2023-02-12 21:10
duplicate of #427

**Closed by sfan5** 2023-02-12 21:10 UTC
Labels: feature request
