### ISSUE TITLE
4K HDR washed out colours on Huawei Mate 10 Pro

### ISSUE THREAD

**Issue by mirkster** [mpv-android/mpv-android#220] opened 2019-11-09 23:32 UTC
Playback of 4K HDR videos results in washed out colours and playback that is not smooth. When using the phones built in video player the same files are playing back perfectly. 

One of the videos I am using for testing is below but it affects all 4K HDR files I have tested it with.
[https://4kmedia.org/lg-colors-of-journey-demo/](url)

The version I am using was downloaded today from the play store, dated 3rd Nov 2019.

**Comment by sfan5** [comment] 2019-11-09 23:53
hwdec enabled? Can you provide a screenshot of on-device rendering with stats.lua Pg1 shown?

**Comment by Doofussy2** [comment] 2019-11-10 06:27
I can partly reproduce this. Some videos there is no tone mapping, others there is significant color banding, and others the picture completely breaks up. I have a Google Pixel 4 XL, and here's a screenshot playing Chess, with the stats.

![Screenshot_20191109-221928 1](https://user-images.githubusercontent.com/15950919/68539948-b607aa00-033f-11ea-8a47-28d39d6bfc15.png)

**Comment by mirkster** [comment] 2019-11-10 21:18
I tested with the Chess Demo file and what do you know, it plays with the correct colour. Motion is still a bit jerky though. Here are screenshots with stats of one demo file that plays displays correct colours and my original test file that doesnt.

Both are with hardware decoding enabled.

![2019-11-10 21 05 40](https://user-images.githubusercontent.com/6277760/68550870-fa0db400-03fe-11ea-94cf-5b6f66f82c7b.jpg)

![2019-11-10 21 06 29](https://user-images.githubusercontent.com/6277760/68550874-00039500-03ff-11ea-91b8-3d8170356427.jpg)

**Comment by Doofussy2** [comment] 2019-11-10 21:36
The difference is the container. I used an mkv for Chess, you're using mp4. But look at the primaries in your second picture. They are wrong, and it's an mkv, also.

**Comment by Doofussy2** [comment] 2019-11-20 06:00
And the motion is jerky because it's dropping a lot of frames. These demo videos are a huge amount to decode and process. They are 59fps, with tone mapping. That's a lot for my RTX 2060 to handle, let alone a phone. Which actually brings me to a side note. Clearly, in your Chess screenshot the colors are oversaturated. I think it's still using the old algorithms and not haasn's new stuff. And on the mobile app, if `hdr-compute-peak` is active, that should be disabled by default. A phone isn't going to have enough juice for that. Maybe they can update the app with the new stuff and the `hdr-compute-peak=auto` will be enough to not enable it on these mobile devices. I have a mini PC with an Intel UHD-600, that can't handle `hdr-compute-peak` without dropping a lot of frames.

**Comment by sfan5** [comment] 2019-11-20 17:01
> That's a lot for my RTX 2060 to handle

Is it?
With `profile=gpu-hq`, `hdr-compute-peak=yes` and `hwdec=nvdec` I get frame timings around 8000us and zero dropped frames on my 1050 Ti all while nvidia-smi reports 55% GPU utilization.

> I think it's still using the old algorithms and not haasn's new stuff.

Unless you are using 2018-04-29 or older, this won't be the case. All newer builds include haasn's peak detection changes.

>  A phone isn't going to have enough juice for that.

In fact, my phone does not support the required features and I doubt higher-end devices do either.
`V mpv     : [vo/gpu:v] Disabling HDR peak computation (one or more of the following is not supported: compute shaders=0, SSBO=0).`

**Comment by Doofussy2** [comment] 2019-11-20 22:29
Well yeah, nvdec with opengl is faster, sadly I can't use that. I upgraded from a GTX 1060 to the RTX 2060, because it was dropping frames with d3d11. But that doesn't apply here. It's good to know that peak detection isn't applied on mobile.

As for the tone mapping, I can see that haasn's update doesn't look like it's being applied. I'll have to retest that, to confirm.

And for this issue, is it container related? It looks like it is.

**Comment by sfan5** [comment] 2020-09-03 22:38
probably fixed by https://github.com/mpv-player/mpv/pull/7849 (also #276)

**Closed by sfan5** 2020-09-03 22:38 UTC
Labels: bug, hwdec
