### ISSUE TITLE
Question/Feature - Launch playback in background

### ISSUE THREAD

**Issue by sou7611** [mpv-android/mpv-android#381] opened 2021-03-12 14:44 UTC
Is it possible (or can it be added) to launch music/audio playback in the background, so the UI screen doesn't appear?

Currently when you sent an intent to launch music playback, it always foregrounds.  You have to actively select background once the playback has started via the UI.

It would be nice if there could be a flag or parameter that could automatically background the playback.

**Comment by sfan5** [comment] 2021-03-12 15:16
It would be possible to add this, yes.
also duplicate of #151

**Closed by sfan5** 2021-03-12 15:16 UTC
