### ISSUE TITLE
Controller input in 2019-04-18

### ISSUE THREAD

**Issue by bennyhillthebest** [mpv-android/mpv-android#184] opened 2019-05-10 10:55 UTC
Hello, i just upgraded mpv on my Shield TV. I like this release a lot (some videos with weird internal subtitles now work flawlessly in SW mode), but i cannot use the Shield controller or an Xbox 360 controller to select the options on the on-screen menu, while with a mouse i can. Is there some way i can solve this? Can i edit input.conf to solve this?

**Comment by sfan5** [comment] 2019-10-04 16:17
Using the UI with a controller is currently not possible.
Also, duplicate of #106

**Closed by sfan5** 2019-10-04 16:17 UTC
