### ISSUE TITLE
Some devices can't play HEVC yuv444p10 with both HW and SW

### ISSUE THREAD

**Issue by NewUserHa** [mpv-android/mpv-android#513] opened 2022-03-23 18:30 UTC
### Important information

Android version: 10
mpv-android version: 3.0.6

### Description

mpv-android on some devices with HW and SW both can't play HEVC yuv444p10 that VLC can play.
mpv-android on some other devices both HW and SW can play though.

**Comment by sfan5** [comment] 2022-03-23 20:07
> mpv-android version: 3.0.6

There is no such mpv-android version.

Anyway, this is probably a duplicate of #507.

**Closed by sfan5** 2022-03-23 20:07 UTC

**Comment by NewUserHa** [comment] 2022-03-23 20:11
typo. it's 2022-03-06.

In theory, SW should be able to play HEVC yuv444p10. because even if HW is not available, VLC could play it.

Can mpv fix the issue?

**Comment by NewUserHa** [comment] 2022-03-23 20:19
by the way, this is not a duplicate of https://github.com/mpv-android/mpv-android/issues/507.
because H264 10bit can't be HW from the start, but HEVC 10bit and HEVC 10bit YUV444 can.

**Comment by sfan5** [comment] 2022-03-23 20:23
It could fundamentally be the same issue but you did not provide a log so not like I could tell.

**Comment by NewUserHa** [comment] 2022-03-23 20:25
ok.

**Comment by NewUserHa** [comment] 2022-03-23 20:43
`mpv-android-2021-10-28.apk` no help, doesn't work too.
