### ISSUE TITLE
Was "Invalid Protocol" intentionally implemented to not let us play torrent/xdcc because the dev is still coping not able add script support or dependencies - curl,wget,node.js

### ISSUE THREAD

**Issue by aicynide** [mpv-android/mpv-android#738] opened 2023-06-25 19:25 UTC
### Important information

Android version:

mpv-android version: 2023-06-04

Which version of mpv-android introduced the problem (if known):

### Description

Describe your issue in detail here.

If the circumstances in which it appears are not obvious, provide step-by-step instructions that can be reliably used to reproduce the issue.

I don't understand what's the need of it. Let us play anything whether its binary, exectuable or pdf file

### Log output

The Android SDK includes a tool named [`logcat`](https://developer.android.com/studio/command-line/logcat) that is used to view application and system log messages on device.
You will need a computer to view these logs.
Logs pertaining to mpv can be collected like this:

	adb logcat -s 'mpv:*' '*:F'

You can attach text files on Github directly or use sites like https://0x0.st/ to upload your logs.
Depending on the nature of the bug, a log file might not be required and you can *omit this section*. If in doubt provide one, it will help us find possible issues later.

### Additional information

If your issue is only reproducible with a specific (type of) file, provide a short sample file that can be used to reproduce the problem.
You can again use https://0x0.st/ or other cloud storage to share it.

If your issue relates to a certain set of configuration options, provide a full copy of your `mpv.conf` below.

If no additional information is provided please *delete this section*.

**Comment by sfan5** [comment] 2023-06-26 08:03
duplicate of #685

**Closed by sfan5** 2023-06-26 08:03 UTC
