### ISSUE TITLE
File name as title

### ISSUE THREAD

**Issue by JimPancakes** [mpv-android/mpv-android#752] opened 2023-07-29 15:56 UTC
I've ticked the Display media title in the options but unfortunately what it probably shows is a internal name or sometimes a number which is not always helpful. Ive tried adding --title=${filename} or variants of it to mpv.conf but it doesn't work. Is there any way ro achieve this currently or if not can it please be implemented?

**Comment by sfan5** [comment] 2023-07-29 16:00
duplicate of #578, whose root cause is #542

other than using the legacy file picker no current fix available.

**Closed by sfan5** 2023-07-29 16:00 UTC
Labels: feature request
