### ISSUE TITLE
Cache is cleared when app put in background

### ISSUE THREAD

**Issue by KaKi87** [mpv-android/mpv-android#358] opened 2021-02-03 20:08 UTC
Hello,

Please prevent app cache from being cleared unless user goes back to home or actually quit the app.

Thanks !

**Comment by sfan5** [comment] 2021-02-22 16:23
Cache is already preserved in some cases (4e7916ea995e07ad09eb4285c2b2f23c4f891cd1), this is currently a deliberate choice to skip video downloading and decoding when a video is backgrounded.

**Comment by KaKi87** [comment] 2021-02-22 16:55
Here's a use case :
1. I am watching a video
2. I receive a notification from some app
3. I click on it and do something with it
4. I go back to mpv

Expected : cache is preserved, video resumes from it

Actual : cache was cleared, video is downloading again

Thanks

**Comment by sfan5** [comment] 2021-02-22 17:03
I know that there are reason to preserve the cache and this bug will eventually be fixed.

**Comment by sfan5** [comment] 2022-03-20 19:28
fixed since e185cdf53429653e3923a16f7453d7c523310319

**Comment by jmir1** [comment] 2022-12-16 01:54
As far as I can tell, when using the latest release or building from source, the cache is still dropped whenever onSurfaceDestroyed is called.
Maybe vo=null isn't the right approach anymore?

**Comment by sfan5** [comment] 2022-12-16 10:23
Switching the vo does not drop cache, what are you basing your assumption on?

**Comment by jmir1** [comment] 2022-12-16 10:58
I'm just guessing around, because this was my experience when using the app.
Whenever I put it into the background or enable the background service, the cache is deleted.
Does this not happen for you?
I've attached a video showing the issue:

https://user-images.githubusercontent.com/43830312/208083838-109ac390-ab35-432c-8604-9e9cff60223b.mp4

**Comment by sfan5** [comment] 2022-12-20 18:03
Can reproduce, will investigate.

**Comment by sfan5** [comment] 2022-12-20 18:24
I have just confirmed that the cache is kept when switching *to* background but keeping caching when switching *from* background has never worked. :thinking:

**Comment by jmir1** [comment] 2022-12-20 18:34
So changing the --wid option makes mpv drop the cache?
Although the [manual](https://mpv.io/manual/master/#options-wid) doesn't make any hints about that...

**Comment by jmir1** [comment] 2023-10-22 21:22
Is there any news on this?

I did some digging in the mpv code but I'm quite inexperienced with that codebase and couldn't find the exact spot in the code where mpv decides to drop the cache.

Also, it seems to be possible to keep the audio cache with some tricks but then you can't re-enable the video again... Looking at the cache statistics, it appears that *only* the audio cache is kept, video is still deleted.

**Comment by sfan5** [comment] 2023-10-22 22:11
Not fixed. I have an experimental patch locally but it needs more work.

mpv executes a so-called refresh seek on the current position when the VO is switched, and the cache is dropped right here:
https://github.com/mpv-player/mpv/blob/05e6813eb2088477ab94607f5a2199da161beb48/demux/demux.c#L3929-L3935
Just skipping this of course does not work for reasons I don't remember (I last worked on this last December) and it's all very complex so be prepared to bring lots of time if you want to investigate.

**Comment by jmir1** [comment] 2023-10-22 22:18
Thanks for the hint, I'll do my best and get back to you if I found something

**Comment by jmir1** [comment] 2024-01-18 16:25
@sfan5 what do you think of this: https://github.com/jmir1/mpv/commit/c7cccdf9e3688bea56e0c3ad68f40ea3b70ef914 ?
I've only tested it on android and it seems to work as intended there, but it probably breaks stuff elsewhere.
On other platforms, switching the vo might be done for different reasons, but on android, I think it only happens when attaching the surface. In this case, the selected tracks don't change at all so a refresh seek should be unnecessary.
Let me know if I made some mistakes in my logic here.

**Comment by sfan5** [comment] 2024-01-19 13:49
That would be an incredible simplification compared to the changes I was thinking were necessary. I'll investigate it later.

**Comment by jmir1** [comment] 2024-01-22 15:30
[this](https://github.com/mpv-player/mpv/pull/13315) got merged now so i guess this issue can finally be closed with the next release

**Closed** 2024-01-22 17:43 UTC
Labels: bug
