### ISSUE TITLE
Crashes wirth jellyfin-android with version 2024-08-20

### ISSUE THREAD

**Issue by enter-a-random-username** [mpv-android/mpv-android#982] opened 2024-08-29 16:43 UTC
### Important information

Android version: 10

mpv-android version: latest fdroid  2024-08-20-release

Which version of mpv-android introduced the problem (if known):
2024-08-20-release

### Description

Crashes while opening a file from jellyfin offical app

### Log output
	adb logcat -s 'mpv:*' '*:F' - nothing

via grep

```
W is.xyz.mpv: Accessing hidden method Landroid/view/WindowInsets$Type;->ime()I (blacklist, linking, denied)
W is.xyz.mpv: Accessing hidden method Landroid/view/WindowInsetsAnimationController;->getTypes()I (blacklist, linking, denied)
W is.xyz.mpv: Accessing hidden method Landroid/view/WindowInsetsAnimationController;->getShownStateInsets()Landroid/graphics/Insets; (blacklist, linking, denied)
W is.xyz.mpv: Accessing hidden method Landroid/view/View;->getWindowInsetsController()Landroid/view/WindowInsetsController; (blacklist, linking, denied)
W is.xyz.mpv: Accessing hidden method Landroid/view/WindowInsetsController;->show(I)V (blacklist, linking, denied)
W is.xyz.mpv: Accessing hidden method Landroid/view/WindowInsetsAnimationController;->getCurrentInsets()Landroid/graphics/Insets; (blacklist, linking, denied)
W is.xyz.mpv: Accessing hidden method Landroid/view/WindowInsetsController;->hide(I)V (blacklist, linking, denied)
W is.xyz.mpv: Accessing hidden method Landroid/view/WindowInsetsAnimationController;->getHiddenStateInsets()Landroid/graphics/Insets; (blacklist, linking, denied)
W is.xyz.mpv: Accessing hidden method Landroid/view/WindowInsets$Builder;->setInsets(ILandroid/graphics/Insets;)Landroid/view/WindowInsets$Builder; (blacklist, linking, denied)
W is.xyz.mpv: Accessing hidden method Landroid/view/WindowInsets$Builder;->setVisible(IZ)Landroid/view/WindowInsets$Builder; (blacklist, linking, denied)
W is.xyz.mpv: Accessing hidden method Landroid/view/Window;->getInsetsController()Landroid/view/WindowInsetsController; (blacklist, linking, denied)
W is.xyz.mpv: Accessing hidden method Landroid/view/WindowInsets;->isVisible(I)Z (blacklist, linking, denied)
W is.xyz.mpv: Accessing hidden method Landroid/view/WindowInsets;->getInsets(I)Landroid/graphics/Insets; (blacklist, linking, denied)
W is.xyz.mpv: Accessing hidden method Landroid/view/WindowInsets$Type;->systemGestures()I (blacklist, linking, denied)
W is.xyz.mpv: Accessing hidden method Landroid/view/WindowInsets$Type;->mandatorySystemGestures()I (blacklist, linking, denied)
W is.xyz.mpv: Accessing hidden method Landroid/view/WindowInsets$Type;->tappableElement()I (blacklist, linking, denied)
V mpv     : Skipping copy of asset file (exists same size): subfont.ttf
V mpv     : Skipping copy of asset file (exists same size): cacert.pem
E AndroidRuntime: Process: is.xyz.mpv, PID: 28092
E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{is.xyz.mpv/is.xyz.mpv.MPVActivity}: java.lang.ClassCastException: android.os.Parcelable[] cannot be cast to android.net.Uri[]
E AndroidRuntime:        at is.xyz.mpv.MPVActivity.parseIntentExtras(MPVActivity.kt:999)
E AndroidRuntime:        at is.xyz.mpv.MPVActivity.onCreate(MPVActivity.kt:305)
W ActivityManager: crash : is.xyz.mpv,0
```

### Additional information

- Deleted all cache and settings for the app inside storage for the app
- Direct play work
- jellyfin android works with old version
- Only on some Android devices
- Downgrade is my current workaround

**Comment by Codling** [comment] 2024-08-29 19:46
Same issue on a NVIDIA Shield TV Pro.

**Comment by sfan5** [comment] 2024-08-29 21:42
duplicate of #980

**Closed by sfan5** 2024-08-29 21:42 UTC
