### ISSUE TITLE
How to use or disable certain touch gestures?

### ISSUE THREAD

**Issue by JoinnA** [mpv-android/mpv-android#226] opened 2020-01-12 04:57 UTC
Hello,

is there a possibility to use or disable only certain touch gestures e.g. brightness?

**Comment by JoinnA** [comment] 2020-01-12 19:28
May be possible if a command is added to mpv.config or is supported in the future.

**Comment by just12** [comment] 2020-01-19 00:31
Doble tap to toggle between pause and play would be nice too.

**Comment by sfan5** [comment] 2020-01-19 14:16
duplicate of #133

**Closed by sfan5** 2020-01-19 14:16 UTC
Labels: duplicate, feature request
