### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Lucky390163** [mpv-android/mpv-android#825] opened 2023-12-08 05:18 UTC
Only two problems app always use hw+ or Sw Decoder.
It does not attempt the HW decoder on the first video played.

App is not properly playing resumed video it always starts from the beginning.Even i viewed and enabled options in settings properly

**Comment by seisdr** [comment] 2023-12-08 18:29
Why am I hearing audio when volume is zero ?

**Comment by Lucky390163** [comment] 2023-12-09 01:56
Sorry, I am new in github.But please fix it

**Comment by sfan5** [comment] 2023-12-12 17:19
That is well-intentioned but it really doesn't work like that.

> App is not properly playing resumed video it always starts from the beginning.Even i viewed and enabled options in settings properly

Most likely a duplicate of #542. No way to tell without seeing the log.

> It does not attempt the HW decoder on the first video played.

This could be anything. I can't even take a guess without seeing the log.

**Closed by sfan5** 2023-12-12 17:19 UTC
