### ISSUE TITLE
APK is missing x86/x86_64 build of libraries

### ISSUE THREAD

**Issue by soredake** [mpv-android/mpv-android#27] opened 2016-08-21 11:53 UTC
Crashes on opening any video
logcat 
[event.log.zip](https://github.com/mpv-android/mpv-android/files/487042/event.log.zip)

RR 5.7.3, x86_64, Z00A

**Comment by Floens** [comment] 2016-08-21 12:13
The stack traces seem to be filtered out in the log that you linked. Check manually if you see any trace for java or for the native code.
But the issue is clear I think, the current build script compiles for arm and you're trying to run it on x86.

**Comment by xyzz** [comment] 2016-08-21 12:16
Yeah most intel devices will attempt to emulate arm libraries (for better compatibility), which sometimes does not work. You will probably need to adjust build scripts to compile for x86_64.

**Comment by kokoko3k** [comment] 2017-03-06 12:38
I'm facing the same issue trying it on a x86 zenfone2.
@xyzz : Could you please be more specific about how to change the build script to compile X86 too?

**Comment by kokoko3k** [comment] 2017-03-06 14:03
Ok, i tried buildall.sh --arch x86_64 but it said me it is an unsupported architecture.
So i edited:
download.sh
``` 
# ndk-toolchain
cd "android-ndk-${v_ndk}"
toolchain_api=21
./build/tools/make_standalone_toolchain.py \
    --arch arm --api $toolchain_api \
    --install-dir `pwd`/../ndk-toolchain
./build/tools/make_standalone_toolchain.py \
    --arch arm64 --api $toolchain_api \
    --install-dir `pwd`/../ndk-toolchain-arm64

./build/tools/make_standalone_toolchain.py \
    --arch x86 --api $toolchain_api \
    --install-dir `pwd`/../ndk-toolchain-x86

./build/tools/make_standalone_toolchain.py \
    --arch x86_64 --api $toolchain_api \
    --install-dir `pwd`/../ndk-toolchain-x86_64
```
...and buildall.sh:
```
loadarch () {
    if [ "$1" == "armv7l" ]; then
        export ndk_suffix=
        export ndk_triple=arm-linux-androideabi
        export dir_suffix=
    elif [ "$1" == "arm64" ]; then
        export ndk_suffix=-arm64
        export ndk_triple=aarch64-linux-android
        export dir_suffix=64
    elif [ "$1" == "x86" ]; then
        export ndk_suffix=-x86
        export ndk_triple=i686-linux-android
        export dir_suffix=
    elif [ "$1" == "x86_64" ]; then
        export ndk_suffix=-x86_64
        export ndk_triple=x86_64-linux-android
        export dir_suffix=
    else
        echo "Invalid architecture"
        exit 1
    fi
}
```
It compiled everything via ./buildall.sh --arch x86_64, but then it said:
```/tmp/buildscripts
~/tmp/buildscripts/mpv-android ~/tmp/buildscripts
Android NDK: ERROR:jni/Android.mk:swresample: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /root/tmp/buildscripts/mpv-android/../prefix64/lib/libswresample.so exists  or that its path is correct   
make: Entering directory `/home/root/tmp/buildscripts/mpv-android/app/src/main'
/home/root/tmp/buildscripts/sdk/android-ndk-r13b/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
make: Leaving directory `/home/root/tmp/buildscripts/mpv-android/app/src/main'
```
...so i tried to force it badly with ln -s prefix prefix64 and tried again  ./buildall.sh --arch x86_64 :
```
~/tmp/buildscripts
~/tmp/buildscripts/mpv-android ~/tmp/buildscripts
make: Entering directory `/home/root/tmp/buildscripts/mpv-android/app/src/main'
[armeabi-v7a] Prebuilt       : libavcodec.so <= /root/tmp/buildscripts/mpv-android/../prefix//lib/
[armeabi-v7a] Install        : libavcodec.so => libs/armeabi-v7a/libavcodec.so
/home/root/tmp/buildscripts/sdk/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip:./libs/armeabi-v7a/libavcodec.so: File format not recognized
make: *** [libs/armeabi-v7a/libavcodec.so] Error 1
make: *** Deleting file `libs/armeabi-v7a/libavcodec.so'
make: Leaving directory `/home/root/tmp/buildscripts/mpv-android/app/src/main'
```

I'm a bit lost at the moment, what should i do?

**Comment by xyzz** [comment] 2017-03-06 14:05
You also need to edit scripts in `scripts/`, for example,  `ffmpeg.sh` has its own arch detection.

**Comment by kokoko3k** [comment] 2017-03-06 14:44
Thanks, i edited scripts/ffmpeg.sh:
```
cpu=armv7-a
[[ "$ndk_triple" == "aarch64"* ]] && cpu=armv8-a
[[ "$ndk_triple" == "i686"* ]] && cpu=i686
[[ "$ndk_triple" == "x86_64"* ]] && cpu=x86_64
```
and checked that ffmpeg configured script was launched that way:
```
./configure     --target-os=android --enable-cross-compile --cross-prefix=x86_64-linux-android-     --arch=x86_64 --cpu=x86_64 --enable-jni --enable-mediacodec     --disable-static --enable-shared     --prefix=/root/tmp/buildscripts/deps/ffmpeg/_build/../../../prefix --disable-debug --disable-doc
```
...which seems fine to me.
i've still had to ln prefix64 to prefix, but now i'm getting the following:
```
Building mpv-android...
~/tmp/buildscripts/mpv-android ~/tmp/buildscripts
EXECUTING ../scripts/mpv-android.sh build ******************************
EXECUTING PREFIX=/root/tmp/buildscripts/mpv-android/../prefix/ PREFIX64=/root/tmp/buildscripts/mpv-android/../prefix64 NDK_TOOLCHAIN_VERSION=4.9 ndk-build -C app/src/main
/root/tmp/buildscripts/sdk/android-ndk-r13b/ndk-build

make: Entering directory `/home/root/tmp/buildscripts/mpv-android/app/src/main'
[armeabi-v7a] Install        : libavcodec.so => libs/armeabi-v7a/libavcodec.so
[armeabi-v7a] Install        : libavdevice.so => libs/armeabi-v7a/libavdevice.so
[armeabi-v7a] Install        : libavfilter.so => libs/armeabi-v7a/libavfilter.so
[armeabi-v7a] Install        : libavformat.so => libs/armeabi-v7a/libavformat.so
[armeabi-v7a] Install        : libavutil.so => libs/armeabi-v7a/libavutil.so
[armeabi-v7a] Install        : libmpv.so => libs/armeabi-v7a/libmpv.so
[armeabi-v7a] Compile++ thumb: player <= main.cpp
[armeabi-v7a] Compile++ thumb: player <= android_content.cpp
[armeabi-v7a] SharedLibrary  : libplayer.so
[armeabi-v7a] Install        : libplayer.so => libs/armeabi-v7a/libplayer.so
[armeabi-v7a] Install        : libswresample.so => libs/armeabi-v7a/libswresample.so
[armeabi-v7a] Install        : libswscale.so => libs/armeabi-v7a/libswscale.so
[arm64-v8a] Install        : libavcodec.so => libs/arm64-v8a/libavcodec.so
[arm64-v8a] Install        : libavdevice.so => libs/arm64-v8a/libavdevice.so
[arm64-v8a] Install        : libavfilter.so => libs/arm64-v8a/libavfilter.so
[arm64-v8a] Install        : libavformat.so => libs/arm64-v8a/libavformat.so
[arm64-v8a] Install        : libavutil.so => libs/arm64-v8a/libavutil.so
[arm64-v8a] Install        : libmpv.so => libs/arm64-v8a/libmpv.so
[arm64-v8a] Compile++      : player <= main.cpp
[arm64-v8a] Compile++      : player <= android_content.cpp
[arm64-v8a] SharedLibrary  : libplayer.so
./obj/local/arm64-v8a/libswresample.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
make: *** [obj/local/arm64-v8a/libplayer.so] Error 1
make: Leaving directory `/home/root/tmp/buildscripts/mpv-android/app/src/main'
```

Grrr, what am i missing now?

**Comment by sfan5** [comment] 2017-03-06 14:53
You need a different `dir_suffix` for each arch, otherwise it will break badly.

**Comment by kokoko3k** [comment] 2017-03-07 08:10
I made different dir_suffix.
buildall.sh:
```
loadarch () {
	if [ "$1" == "armv7l" ]; then
		export ndk_suffix=
		export ndk_triple=arm-linux-androideabi
		export dir_suffix=armv7l
	elif [ "$1" == "arm64" ]; then
		export ndk_suffix=-arm64
		export ndk_triple=aarch64-linux-android
		export dir_suffix=arm64
	elif [ "$1" == "x86" ]; then
		export ndk_suffix=-x86
		export ndk_triple=i686-linux-android
		export dir_suffix=x86
	elif [ "$1" == "x86_64" ]; then
		export ndk_suffix=-x86_64
		export ndk_triple=x86_64-linux-android
		export dir_suffix=x86_64
	else
		echo "Invalid architecture"
		exit 1
	fi
}
```
Then did the usual link prefix to prefix64 and /buildall.sh --clean --arch x86_64
But still:
```
make: Entering directory `/home/root/tmp/buildscripts/mpv-android/app/src/main'
[armeabi-v7a] Prebuilt       : libavcodec.so <= /root/tmp/buildscripts/mpv-android/../prefix//lib/
[armeabi-v7a] Install        : libavcodec.so => libs/armeabi-v7a/libavcodec.so
[armeabi-v7a] Prebuilt       : libavdevice.so <= /root/tmp/buildscripts/mpv-android/../prefix//lib/
[armeabi-v7a] Install        : libavdevice.so => libs/armeabi-v7a/libavdevice.so
[armeabi-v7a] Prebuilt       : libavfilter.so <= /root/tmp/buildscripts/mpv-android/../prefix//lib/
[armeabi-v7a] Install        : libavfilter.so => libs/armeabi-v7a/libavfilter.so
[armeabi-v7a] Prebuilt       : libavformat.so <= /root/tmp/buildscripts/mpv-android/../prefix//lib/
[armeabi-v7a] Install        : libavformat.so => libs/armeabi-v7a/libavformat.so
[armeabi-v7a] Prebuilt       : libavutil.so <= /root/tmp/buildscripts/mpv-android/../prefix//lib/
[armeabi-v7a] Install        : libavutil.so => libs/armeabi-v7a/libavutil.so
[armeabi-v7a] Prebuilt       : libmpv.so <= /root/tmp/buildscripts/mpv-android/../prefix//lib/
[armeabi-v7a] Install        : libmpv.so => libs/armeabi-v7a/libmpv.so
[armeabi-v7a] Compile++ thumb: player <= main.cpp
[armeabi-v7a] Compile++ thumb: player <= android_content.cpp
[armeabi-v7a] Prebuilt       : libswresample.so <= /root/tmp/buildscripts/mpv-android/../prefix//lib/
[armeabi-v7a] Prebuilt       : libswscale.so <= /root/tmp/buildscripts/mpv-android/../prefix//lib/
[armeabi-v7a] StaticLibrary  : libstdc++.a
[armeabi-v7a] SharedLibrary  : libplayer.so
[armeabi-v7a] Install        : libplayer.so => libs/armeabi-v7a/libplayer.so
[armeabi-v7a] Install        : libswresample.so => libs/armeabi-v7a/libswresample.so
[armeabi-v7a] Install        : libswscale.so => libs/armeabi-v7a/libswscale.so
[arm64-v8a] Prebuilt       : libavcodec.so <= /root/tmp/buildscripts/mpv-android/../prefix64/lib/
[arm64-v8a] Install        : libavcodec.so => libs/arm64-v8a/libavcodec.so
[arm64-v8a] Prebuilt       : libavdevice.so <= /root/tmp/buildscripts/mpv-android/../prefix64/lib/
[arm64-v8a] Install        : libavdevice.so => libs/arm64-v8a/libavdevice.so
[arm64-v8a] Prebuilt       : libavfilter.so <= /root/tmp/buildscripts/mpv-android/../prefix64/lib/
[arm64-v8a] Install        : libavfilter.so => libs/arm64-v8a/libavfilter.so
[arm64-v8a] Prebuilt       : libavformat.so <= /root/tmp/buildscripts/mpv-android/../prefix64/lib/
[arm64-v8a] Install        : libavformat.so => libs/arm64-v8a/libavformat.so
[arm64-v8a] Prebuilt       : libavutil.so <= /root/tmp/buildscripts/mpv-android/../prefix64/lib/
[arm64-v8a] Install        : libavutil.so => libs/arm64-v8a/libavutil.so
[arm64-v8a] Prebuilt       : libmpv.so <= /root/tmp/buildscripts/mpv-android/../prefix64/lib/
[arm64-v8a] Install        : libmpv.so => libs/arm64-v8a/libmpv.so
[arm64-v8a] Compile++      : player <= main.cpp
[arm64-v8a] Compile++      : player <= android_content.cpp
[arm64-v8a] Prebuilt       : libswresample.so <= /root/tmp/buildscripts/mpv-android/../prefix64/lib/
[arm64-v8a] Prebuilt       : libswscale.so <= /root/tmp/buildscripts/mpv-android/../prefix64/lib/
[arm64-v8a] StaticLibrary  : libstdc++.a
[arm64-v8a] SharedLibrary  : libplayer.so
./obj/local/arm64-v8a/libswresample.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
make: *** [obj/local/arm64-v8a/libplayer.so] Error 1
make: Leaving directory `/home/root/tmp/buildscripts/mpv-android/app/src/main'
``

**Comment by kokoko3k** [comment] 2017-03-07 08:41
I made a step forward.
in mpv-android.sh:
```
#PREFIX=`pwd`/../prefix/ PREFIX64=`pwd`/../prefix64 NDK_TOOLCHAIN_VERSION=4.9 ndk-build -C app/src/main
PREFIX=`pwd`/../prefix$dir_suffix/ NDK_TOOLCHAIN_VERSION=4.9 ndk-build -C app/src/main
```
and in Android.mk:
```
#ifeq ($(TARGET_ARCH_ABI),arm64-v8a)
#PREFIX = $(PREFIX64)
#endif
```

**Comment by sfan5** [comment] 2017-03-07 09:01
The problem is that by missing a `dir_suffix` the first time you installed x86_64 files into `prefix64` where it expects 64-bit ARM libraries.

**Comment by sfan5** [comment] 2017-03-07 09:16
Here's proper support btw:
* mpv-android/mpv-android@81b669bf2cb53f8967db7d385480987004916f6b
* mpv-android/buildscripts@caa53db61472d06c2992e57fd517ca4d92acd03c

**Comment by kokoko3k** [comment] 2017-03-07 09:45
I manually merged your modifications and started over.
```
# ./buildall.sh --arch x86_64
[..]
Android NDK: ERROR:jni/Android.mk:swresample: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /root/tmp/mpv-android-new/buildscripts/mpv-android/../prefix64/lib/libswresample.so exists  or that its path is correct   
make: Entering directory `/home/root/tmp/mpv-android-new/buildscripts/mpv-android/app/src/main'
/home/root/tmp/mpv-android-new/buildscripts/sdk/android-ndk-r13b/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
make: Leaving directory `/home/root/tmp/mpv-android-new/buildscripts/mpv-android/app/src/main'

# head mpv-android/app/src/main/jni/Android.mk 
LOCAL_PATH:= $(call my-dir)

ifeq ($(TARGET_ARCH_ABI),arm64-v8a)
PREFIX = $(PREFIX64)
endif

ifeq ($(TARGET_ARCH_ABI),x86_64)
PREFIX = $(PREFIX_X64)
endif

# head mpv-android/app/src/main/jni/Application.mk 
APP_ABI := armeabi-v7a arm64-v8a x86_64
APP_PLATFORM := android-21
```
in buildall.sh i've:
``
    elif [ "$1" == "x86_64" ]; then
        export ndk_suffix=-x64
        export ndk_triple=x86_64-linux-android
        export dir_suffix=-x64
    else
```

SomeHow, my ARGET_ARCH_ABI is wrong.

**Comment by soredake** [comment] 2017-03-07 14:00
@kokoko3k https://github.com/mpv-android/buildscripts/blob/sfan5/x86_64/download.sh#L94 did you changed branch to x86_64 here?

**Comment by kokoko3k** [comment] 2017-03-07 14:42
Nope i didn't, but i managed to make it build somehow and have had a big segmentation fault with coredump/tombstone, i think opengl related, probably mpv related, this time.
Thank you!

**Comment by soredake** [comment] 2017-09-24 17:26
@sfan5 can pls merge x86_64 branch into master?

**Comment by sfan5** [comment] 2017-09-24 19:58
I'd like to make multiarch builds optional before adding yet another arch you have to compile for.

**Comment by soredake** [comment] 2017-10-10 13:45
After
```
apt update
# https://github.com/mpv-android/buildscripts/issues/5
apt install -y git wget apt-utils default-jdk unzip python build-essential m4 pkgconf automake libtool
git clone https://github.com/mpv-android/buildscripts
cd buildscripts
sed -i -e "s/apt-get/apt-get -y/g" -e "s/sudo//g" -e "s|ftp://ftp.gnutls.org/gcrypt/gnutls|https://www.gnupg.org/ftp/gcrypt/gnutls|g" download.sh
./download.sh
./buildall.sh --arch x86_64
cp ./mpv-android/app/build/outputs/apk/app-debug.apk /build
```
i get this https://github.com/mpv-android/mpv-android/issues/27#issuecomment-284671919

**Comment by sfan5** [comment] 2017-10-10 17:08
32-bit ARM support is currently not optional, either build for arm once too (`./buildall.sh mpv`) <b>or</b> remove `armeabi-v7a` from app/src/main/jni/Application.mk

**Comment by soredake** [comment] 2017-10-10 19:00
Now after 
```
apt update
apt install -y git wget apt-utils default-jdk unzip python build-essential m4 pkgconf automake libtool
git clone https://github.com/mpv-android/buildscripts
cd buildscripts
sed -i -e "s/apt-get/apt-get -y/g" -e "s/sudo//g" -e "s|ftp://ftp.gnutls.org/gcrypt/gnutls|https://www.gnupg.org/ftp/gcrypt/gnutls|g" -e "s,\"./android-sdk,echo \'y\' | \"./android-sdk,g" download.sh
./download.sh
echo 'y' | ./sdk/android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-25.0.2,android-25,platform-tools
sed -i -e "s/APP_ABI := armeabi-v7a//g" mpv-android/app/src/main/jni/Application.mk || exit 1
./buildall.sh --arch x86_64
````
 i get 
```
❯ adb install -r app-debug.apk
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
```

**Comment by sfan5** [comment] 2017-10-10 19:13
did it build native code at all? does your apk contain `.so` files?

**Comment by soredake** [comment] 2017-10-10 19:29
It seems my problem is that I did everything from root, after repacking with `zip -r apk.apk ./*` i get `Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl973988772.tmp/base.apk: META-INF/CERT.SF indicates /data/app/vmdl973988772.tmp/base.apk is signed using APK Signature Scheme v2, but no such signature was found. Signature stripped?]`, i'll try with normal user later.

**Comment by soredake** [comment] 2017-10-21 14:07
Tried building from non-root, still `INSTALL_FAILED_NO_MATCHING_ABIS`
>does your apk contain .so files?

Yes

```
  inflating: app-debug/lib/x86_64/libavcodec.so  
  inflating: app-debug/lib/x86_64/libavdevice.so  
  inflating: app-debug/lib/x86_64/libavfilter.so  
  inflating: app-debug/lib/x86_64/libavformat.so  
  inflating: app-debug/lib/x86_64/libavutil.so  
  inflating: app-debug/lib/x86_64/libc++_shared.so  
  inflating: app-debug/lib/x86_64/libmpv.so  
  inflating: app-debug/lib/x86_64/libplayer.so  
  inflating: app-debug/lib/x86_64/libswresample.so  
  inflating: app-debug/lib/x86_64/libswscale.so  
```

**Comment by sfan5** [comment] 2017-10-21 15:34
You'll need to make whatever changes needed (install another ROM) to get your device to load 64-bit libraries then.

I have to admit I didn't check before implementing whether `i686` or `x86_64` is more common amongst Android x86 devices. Maybe it's a good idea for mpv-android to support i686 for compatibility reasons.

**Closed** 2017-12-08 23:14 UTC
