### ISSUE TITLE
[FR] view buffered length in seekbar

### ISSUE THREAD

**Issue by foxjaw** [mpv-android/mpv-android#827] opened 2023-12-10 15:19 UTC
We aren't sure how much did mpv buffer while playing a network stream.  
Showing this length inside seekbar will help us not cross the buffered length in order to avoid loading screen.

**Comment by sfan5** [comment] 2023-12-10 15:25
I agree this would be good but duplicate of #430

**Closed by sfan5** 2023-12-10 15:25 UTC
Labels: feature request
