### ISSUE TITLE
Android TV controls

### ISSUE THREAD

**Issue by PixelDew121** [mpv-android/mpv-android#233] opened 2020-01-18 15:23 UTC
I would like to use the Android app sideloaded on my Firestick, however I cannot use the buttons to navigate. I edited the input.conf to where I used UP for cycle sub and DOWN for cycle audio, however I'm unsure what the command would be if I wanted to access settings or switch between hw/sw decoder.

**Comment by sfan5** [comment] 2020-01-18 18:09
duplicate of #106

> command would be if I wanted to access settings or switch between hw/sw decode

Navigating the menus is impossible as you have noticed, however switching hwdec can be done by binding a key to `cycle-values hwdec no mediacodec-copy`.

**Closed by sfan5** 2020-01-18 18:09 UTC
