### ISSUE TITLE
Show buffering progress 

### ISSUE THREAD

**Issue by kllkko** [mpv-android/mpv-android#693] opened 2023-04-26 05:49 UTC
When playing a video on the network, when the network is not good, it is necessary to display the loading progress or loading state, otherwise the screen will not move and the experience will not be good.

**Comment by sfan5** [comment] 2023-04-26 17:56
It sounds like you want to implement this yourself, please have a look at the [manual](https://mpv.io/manual/master/).
If this is meant as a feature request for mpv-android I can reopen.

**Comment by kllkko** [comment] 2023-04-27 01:20
> It sounds like you want to implement this yourself, please have a look at the [manual](https://mpv.io/manual/master/). If this is meant as a feature request for mpv-android I can reopen.

yes，i mean as a feature request for mpv-android

**Comment by sfan5** [comment] 2023-08-06 17:45
duplicate of #430

**Closed by sfan5** 2023-08-06 17:45 UTC
Labels: feature request, user interface
