### ISSUE TITLE
Gpu-next master android 

### ISSUE THREAD

**Issue by Jamie666123** [mpv-android/mpv-android#754] opened 2023-07-31 19:32 UTC
Describe the wanted behaviour of the new feature and potential usecases for it here.

Hi there just a quick feature request I was just wondering if there was any news on if gpu-next will be coming to the next update for the android version of MPV I understand that it is present in the vulkan test version however it Is clear now in that version that it is stable enough to add for android users using gpu-api=opengl and gpu- context = android so was wondering if this compatibility will be added to the master version I am only asking as I'm sure others will agree that we would like to be able to use the new HDR tonemapping options and other options which are gpu-next only when android is the only device we have to use MPV and it is now been tested that it can be used and is stable with opengl despite vulkan not being stable yet thanks

**Comment by Jamie666123** [comment] 2023-07-31 19:33
I would like to see the gpu-next functionality moved to the master build as it is very stable with gpu-api=opengl and gpu-context= android and at least then me and others will have the option to swap between gpu and gpu-next as we would like to and Vulkan support can continue to be tested in the test version

**Comment by sfan5** [comment] 2023-07-31 19:37
duplicate of #754

**Closed by sfan5** 2023-07-31 19:37 UTC
Labels: feature request
