### ISSUE TITLE
Can't add shader

### ISSUE THREAD

**Issue by Huta0c6** [mpv-android/mpv-android#983] opened 2024-09-02 08:50 UTC
### Important information

Android version: 11

mpv-android version: 2024-08-20-release

Which version of mpv-android introduced the problem (if known):

### Description

 Mpv on Android 11 and above only asks for media access permission. This prevents shader files from being loaded.

**Comment by sfan5** [comment] 2024-09-02 13:50
duplicate of https://github.com/mpv-android/mpv-android/issues/709

**Closed by sfan5** 2024-09-02 13:50 UTC
