### ISSUE TITLE
Arabic cp1256 is not working.

### ISSUE THREAD

**Issue by Zud96** [mpv-android/mpv-android#993] opened 2024-09-15 08:33 UTC
Arabic subtitles with cp1256 charset are displaying incorrect characters. However Arabic UTF-8 subtitles are working correctly. 
Tried using `--sub-codepage=cp1256` and didn't work. 

[Subtitle used](https://github.com/user-attachments/files/17005085/Doctor.who.s05e12.zip)

Android version: 11

mpv-android version:
mpv-android 2024-08-20-release / 8038 (release)
mpv v0.38.0-714-gf44c29b223 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Aug 20 2024 20:49:12
libplacebo version: v7.349.0 (v7.349.0-5-g82bf46ae)
FFmpeg version: N-116752-g507c2a5774
FFmpeg library versions:
   libavcodec      61.11.100
   libavdevice     61.2.100
   libavfilter     10.2.102
   libavformat     61.5.101
   libavutil       59.34.100
   libswresample   5.2.100
   libswscale      8.2.100
Configuration: -Diconv=disabled -Dlua=enabled -Dlibmpv=true -Dcplayer=false -Dmanpage-build=disabled -Ddefault_library=shared --cross-file=/var/tmp/mpv-android/buildscripts/prefix/arm64/crossfile.txt
List of enabled features: android android-media-ndk build-date cplugins dvbin egl-android ffmpeg gl glibc-thread-name gpl libass libavdevice libdl libplacebo linux-fstatfs lua memrchr opensles posix ppoll pthread-condattr-setclock vector vt.h zlib

**Comment by sfan5** [comment] 2024-09-15 09:19
duplicate of #260

**Closed by sfan5** 2024-09-15 09:19 UTC
